export const MESSAGE = {
  AUTHORIZATION_FAIL: "Login Fail",
  USER_NOT_FOUND: "User Not Found",
  INVALID_REQUEST : "Invalid client request",
  FPT_FE: "Email must be end @fpt.edu.vn or @fe.edu.vn",
  AUTHORIZATION: "Don't have permission to access this page",
  INVITE_USER: "Invite User Success",
  GET_DATA_FAIL: "Server down",
  CREATE_FAIL: "Create Fail",
  UPDATE_FAIL: "Update Fail",
  DELETE_FAIL: "Delete Fail",
  CHOOSE_IMAGE: "Please Choose Image PNG, JPGE, JPG",
  CREATE_PROJECT_SUCCESS: "Project has been created",
  PROJECT_NAME_EXIST: "Project Name already Exist",
  UPDATE_PROJECT_SUCCESS: "Project has been updated",
  DELETE_PROJECT_SUCCESS: "Project has been deleted",
  CREATE_SPRINT_SUCCESS: "Sprint has been created",
  SPRINT_NAME_EXIST: "Sprint Name already Exist",
  UPDATE_SPRINT_SUCCESS: "Sprint has been updated",
  DELETE_SPRINT_SUCCESS: "Sprint has been deleted",
  CREATE_ISSUE_SUCCESS: "Issue has been created",
  UPDATE_ISSUE_SUCCESS: "Issue has been updated",
  DELETE_ISSUE_SUCCESS: "Issue has been deleted",
  UPDATE_USER_SUCCESS: "User has been updated",
  CREATE_SUB_ISSUE_SUCCESS: "SubIssue has been created",
  UPDATE_SUB_ISSUE_SUCCESS: "SubIssue has been updated",
  DELETE_SUB_ISSUE_SUCCESS: "SubIssue has been deleted",
  CREATE_COMMENT_SUCCESS: "Comment has been created",
  UPDATE_COMMENT_SUCCESS: "Comment has been updated",
  DELETE_COMMENT_SUCCESS: "Comment has been deleted",
}
export const ACCESS_TOKEN = "access_token";
export const REFRESH_TOKEN = "refresh_token";